version: '3.8'
services:
  antink-server:
    build: .
    container_name: antink-server
    privileged: true
    volumes:
      - ./it24_host:/it24_host
      - ./antink_mount:/antink_mount
      - ./antink-logs:/var/log
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

  antink-logger:
    image: ubuntu:22.04
    container_name: antink-logger
    command: tail -f /var/log/it24.log
    volumes:
      - ./antink-logs:/var/log
